### ISSUE TITLE
Apply RuntimeOnly to whole enum?

### ISSUE THREAD

**Issue by Yustie** [timabell/ef-enum-to-lookup#10]
Hi,

Can I apply RuntimeOnly attribute to a whole enum, or only to enum values? I have an enum which can be completely RuntimeOnly.

Another question I have is, how to add a collection of enums to a list/icollection?

**Comment by timabell** [comment]
I can't think of a use-case for this so I'm going to close it. If you have a reason for needing this then add details here, otherwise it won't be supported.
