### ISSUE TITLE
InvalidCastException when using non-Int Enum values such as byte.

### ISSUE THREAD

**Issue by martinlaukkanen** [timabell/ef-enum-to-lookup#20]
Exception:
System.InvalidCastException: System.InvalidCastException: Specified cast is not valid.
   at EfEnumToLookup.LookupGenerator.EnumToLookup.GetLookupValues(Type lookup) in c:\repo\ef-enum-to-lookup\EfEnumToLoo
kup\LookupGenerator\EnumToLookup.cs:line 149

If I change my enum values from byte to int it works fine.

**Comment by timabell** [comment]
Thanks for the feedback, I'll take a look when I get some time. If you wish to provide a pull request with a new test case and fix you're more than welcome to.

**Comment by timabell** [comment]
http://stackoverflow.com/a/3213790/10245 - handling of other types

**Comment by timabell** [comment]
1.6.0 released with this fix, please test and report back, thanks
https://www.nuget.org/packages/ef-enum-to-lookup

I learnt new things about c# while doing this :-)

**Comment by timabell** [comment]
@martinlaukkanen did you try the new version?
