### ISSUE TITLE
Add Created column

### ISSUE THREAD

**Issue by sveinhelge** [timabell/ef-enum-to-lookup#34]
Would like to have the ability to have a Created column.

The table would then look like this:
Id
Name
Description
Created

It could be implemented as a setting.
var enumToLookup = new EnumToLookup();
enumToLookup.AddCreatedColumn = true;

This column would hold the the created date and time for the insert. This way you could easily see when a specific Enum value was added without searching source code repository.

**Comment by timabell** [comment]
I'm not keen on this, so I'll decline this one.

I think people should always be able to look at source-control.
I can see the extra data ending up being confusing, as it wouldn't be clear what it really means.
I can't think of a use-case for this information (feel free to provide one, though I can't promise I'll change my mind!)

**Comment by sveinhelge** [comment]
When you have a data warehouse solution pulling data from your database this comes in handy when some mapping fails on their side. The people pulling data to the data warehouse solution normally don't have access to the source code. Often they are not even developers. So when they get a new Enum name from the table that they have not mapped before, they can check the date to see if the new value was newly added. If it's newly added they know it's because they haven't added that mapping in their universe. If the created date time is old, they would know that they have messed up something.

I don't see the possible confusion. If I see a created column on a data row I would assume it is the date time of the creation of that row.

But this decision is all yours. I think it would be a good idea.
