### ISSUE TITLE
Custom column names for created look up tables

### ISSUE THREAD

**Issue by jprakasan** [timabell/ef-enum-to-lookup#42]
ef-enum-to-lookup helps to create look up table for each Enum in the context.We can set prefix and suffix name for ENUM to Look tables. Like this can we set a custom name for the field in the look up table .

 Now the enum to lookup table has column's ID and Name . Is it possible to give custom name
 eg (' ENUM Name' + ID )  ('ENUM Name'+Name) .

Also is it possible to set the column Name NOT NULL.

Regards ,
Jinesh

**Comment by timabell** [comment]
Can you file a separate issue for the not null thing so we can track progress separately, cheers.

Can I ask why you want to change the column names? Is it causing you a problem? It's not something that's bothered me so far. Obviously this would introduce (minor) extra complexity so I wouldn't add it unless I was sure of the need.

In the mean time, you are of course welcome to fork the project and make whatever adjustments you wish to suit your needs.
