### ISSUE TITLE
Postfix and suffix for foreign key column

### ISSUE THREAD

**Issue by gijsdeboer** [timabell/ef-enum-to-lookup#48]
The foreign key columns that are created by EnumToLookup don't get the 'Id' suffix that I do get when I create a regular EF relationship property.

I can fix this issue by adding the Column attribute on every enum for instance:
[Column("TaxTypeId")]
public TaxType TaxType { get; set; }

It would be nice if I could set a ForeignKey prefix and suffix once that would be added to every Foreign Key column EnumToLookup created. That way, if I would set a TableNameSuffix "Enum" and a ForeignKeySuffix "EnumId", I would get a foreign key column TaxTypeEnumId that would follow my convention <parent tablename><parent keyname>.

**Comment by timabell** [comment]
It's EF creating the column not this library. This library only adds the FK to the existing columns.
