### ISSUE TITLE
Lookup table does not include custom table name syntax

### ISSUE THREAD

**Issue by aldav82** [timabell/ef-enum-to-lookup#49]
When configuring the final table names, the lookup table will not follow the pattern. e.g.

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Types().Configure(entity => entity.ToTable("PREFIX_" + entity.ClrType.Name));
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }

All the generated tables are named "PREFIX_*******" except enum ones, which are called "Enum_XXXXX". This might be a problem when we have multiple applications sharing the same database, given the case both applications have an exactly equally named enum.

**Comment by timabell** [comment]
That's because the lookup tables aren't generated by EF. You can tell this library about your own prefix by setting the `TableNamePrefix` property.

https://github.com/timabell/ef-enum-to-lookup/blob/master/EfEnumToLookup/LookupGenerator/EnumToLookup.cs#L53
