### ISSUE TITLE
Can't create sprocs because lookup tables not in place in time

### ISSUE THREAD

**Issue by maharatha** [timabell/ef-enum-to-lookup#64]
I have been using the ef-enum-to-lookup nuget for sometime now and it has been working fine. Recently we have started using stored procedures and views in the system which now uses value from the Enum tables that's created.

Problem : We are deploying the Stored Proc and Views using EF Migration , but the enum tables are being created at the end of the migration on the seed method which doesn't gets called before all database objects are created. This is throwing up error as the enum tables are not there and the views and stoired procedures are referencing those.

Any idea to tackle this

**Comment by timabell** [comment]
Write a small command line app that references your dbcontext and the lookup generator and spit the generated sql out to a file that you can then put anywhere in your migration workflow.

**Comment by timabell** [comment]
https://github.com/timabell/ef-enum-to-lookup/blob/98fdc0e5f018ae906d075d89d5b63b75e7748f62/ExampleUsage/EnumExample.cs#L43
