### ISSUE TITLE
Naming using attributes

### ISSUE THREAD

**Issue by The-Scary-One** [timabell/ef-enum-to-lookup#66]
Hi,
I have to questions;
1. In your EnumExample.cs you have the following line:
`[System.ComponentModel.Description("It's average")] // example of apostrophe that would need escaping in sql` and `[System.ComponentModel.Description("Huge you know?")] // give it a different name in the lookup table` how is it supposed to change names?
2. Is it possible to rename the 'Name' column? Issue #41 implies it in the title and in the post that  an attribute to do so, but I can't seem to find it any where.

Kind regards

Casper Andersen

**Comment by timabell** [comment]
https://github.com/timabell/ef-enum-to-lookup/blob/master/ExampleUsage/EnumExample.cs#L87

**Comment by timabell** [comment]
1. The attribute you point to modifies the data in the table.
2. Not currently. That's what #41 is for.

**Comment by timabell** [comment]
If you want that feature I'm open to paid work. See #58

**Comment by The-Scary-One** [comment]
Thank you, for your reply.
1. I didn't see a change, might be I did something wrong, though I have no idea what it should be.
2. Than you for your offer, but the change is very far into the 'nice to have' section, especially since requirements changed so it only is possible to use 1 lookup table in the implementation.
